site_name: Aos8APIBuilder for Python Documentation
site_url: https://Samuelyip74.github.io/Aos8ApiBuilder/
site_dir: ../../site
docs_dir: docs

theme:
  name: readthedocs

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["..", "../.."]
          options:
            docstring_style: google
            show_root_heading: false
            show_source: false            

markdown_extensions:
  - smarty
  - toc:
      permalink: true
  - sane_lists

nav:
  - Aos8APIBuilder Classes:
      - Introduction: intro.md
      - Getting Started: getting-started.md
      - Aos8ApiBuilder:
          - ApiBuilder: api/ApiBuilder.md
          - ApiClient: api/ApiClient.md
          - Models: api/models.md
      - API Endpoints:
          - System: endpoints/system.md     
          - Interface: endpoints/interface.md     
          - VLAN: endpoints/vlan.md   
          - MVRP: endpoints/mvrp.md       
          - VPA: endpoints/vpa.md   
          - MAC: endpoints/mac.md       
          - IP: endpoints/ip.md   
      - Helper:   
          - Parser: helper/parser.md     



watch:
  - ../../Aos8APIBuilder
