site_name: Aos8APIBuilder for Python Documentation
site_dir: ../../site
docs_dir: docs
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["..", "../.."]  # Add both current and parent of parent as search paths
          options:
            docstring_style: google          

markdown_extensions:
  - admonition
  - toc:
      permalink: true
